In [2]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

from warnings import filterwarnings
filterwarnings('ignore')

In [3]:
hit = pd.read_csv("Hitters.csv")
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.25, 
                                                    random_state=42)

In [4]:
bag_model=BaggingRegressor(bootstrap_features=True)

In [5]:
bag_model.fit(X_train,y_train)

BaggingRegressor(bootstrap_features=True)

In [7]:
bag_model.estimator_params
bag_model.n_estimators
bag_model.estimators_samples_
bag_model.estimators_features_

[array([ 9,  4, 13,  1, 11,  0, 13, 13,  6,  3,  8,  7,  4, 11,  3,  4,  3,
         4,  1]),
 array([ 3,  5, 12, 12, 12, 10, 18,  7,  6,  2, 11,  4,  9, 11, 13, 17,  4,
        16, 15]),
 array([15,  3, 17, 12, 18, 11,  6,  7,  8, 14, 15,  4,  2, 10, 10,  0, 10,
         8,  3]),
 array([ 8, 12,  1,  6, 15, 16, 17,  6,  1,  2, 11,  0,  8,  5,  2,  7,  0,
         9, 18]),
 array([12,  8,  4,  5,  4, 12, 12, 14,  9, 12,  9, 17, 14,  2, 10,  5,  0,
        10,  4]),
 array([ 9, 12, 14, 10, 14,  2,  3,  0,  0,  7,  7,  5, 17, 14,  9,  3, 17,
        16,  0]),
 array([ 7,  3, 14, 12,  9,  7, 18, 15,  5, 13,  1, 11,  5,  5,  6,  2, 15,
         0,  0]),
 array([ 4,  8, 16, 18, 11, 11,  7,  2, 17,  1, 10,  3,  7,  7, 14,  4,  4,
        15, 11]),
 array([15,  9, 14,  9,  2, 18,  2, 13, 14,  4, 10, 11,  5,  1, 12,  7,  5,
        13,  7]),
 array([11, 11, 16,  2, 15, 15,  2,  6, 15,  4, 16, 17, 18,  7, 10,  6, 15,
         9, 18])]

In [8]:
bag_model.estimators_[1]

DecisionTreeRegressor(random_state=1619429347)

In [9]:
y_pred = bag_model.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred))

376.969726670957

In [10]:
second_y_pred = bag_model.estimators_[1].fit(X_train, y_train).predict(X_test)

In [11]:
np.sqrt(mean_squared_error(y_test, second_y_pred))

434.8797726138766

In [12]:
#If you want you can put a number and change mse

In [13]:
bag_params = {"n_estimators": range(2,20)}

In [14]:
bag_cv_model=GridSearchCV(bag_model,bag_params,cv=10)

In [15]:
bag_cv_model.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=BaggingRegressor(bootstrap_features=True),
             param_grid={'n_estimators': range(2, 20)})

In [16]:
bag_cv_model.best_params_

{'n_estimators': 12}

In [17]:
bag_tuned = BaggingRegressor( n_estimators = 12, random_state = 45)

In [18]:
bag_tuned.fit(X_train, y_train)

BaggingRegressor(n_estimators=12, random_state=45)

In [19]:
y_pred = bag_tuned.predict(X_test)

In [20]:
np.sqrt(mean_squared_error(y_test, y_pred))

346.0633892916423